// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"

	mock "github.com/stretchr/testify/mock"
)

// DbClient is an autogenerated mock type for the DbClient type
type DbClient struct {
	mock.Mock
}

type DbClient_Expecter struct {
	mock *mock.Mock
}

func (_m *DbClient) EXPECT() *DbClient_Expecter {
	return &DbClient_Expecter{mock: &_m.Mock}
}

// GetItem provides a mock function with given fields: ctx, params
func (_m *DbClient) GetItem(ctx context.Context, params *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error) {
	ret := _m.Called(ctx, params)

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput) *dynamodb.GetItemOutput); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DbClient_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type DbClient_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.GetItemInput
func (_e *DbClient_Expecter) GetItem(ctx interface{}, params interface{}) *DbClient_GetItem_Call {
	return &DbClient_GetItem_Call{Call: _e.mock.On("GetItem", ctx, params)}
}

func (_c *DbClient_GetItem_Call) Run(run func(ctx context.Context, params *dynamodb.GetItemInput)) *DbClient_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dynamodb.GetItemInput))
	})
	return _c
}

func (_c *DbClient_GetItem_Call) Return(_a0 *dynamodb.GetItemOutput, _a1 error) *DbClient_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DbClient_GetItem_Call) RunAndReturn(run func(context.Context, *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error)) *DbClient_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDbClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewDbClient creates a new instance of DbClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDbClient(t mockConstructorTestingTNewDbClient) *DbClient {
	mock := &DbClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
